# Generated by Django 5.2.6 on 2025-09-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
