# Generated by Django 5.2.6 on 2025-09-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='item_price',
        ),
    ]
